#!/bin/bash

rm -f CMakeCache.txt
rm -rf CMakeFiles

cmake \
    -D CMAKE_BUILD_TYPE:STRING=RELEASE \
    -D DICE_TRILINOS_DIR:FILEPATH=<path>/trilinos-12.4.2-Source/build/install \
    -D CMAKE_INSTALL_PREFIX:FILEPATH=<path>/DICe/build/install \
    -D CMAKE_VERBOSE_MAKEFILE:BOOL=OFF \
    -D CMAKE_CXX_FLAGS:STRING="-Wno-deprecated-declarations -Wno-format-security" \
    -D DICE_DEBUG_MSG:BOOL=ON \
    -D DICE_USE_DOUBLE:BOOL=ON \
    -D DICE_USE_TPETRA:BOOL=OFF \
    -D DICE_ENABLE_MANYCORE:BOOL=OFF \
    -D DICE_ENABLE_GLOBAL:BOOL=ON \
    -D OpenCV_DIR:PATH=<path>/opencv-3.2.0/build/install \
    ../
